### ISSUE TITLE
Plugin Appears to Break Builds With Gradle 8.1, Causing `org.objectweb.asm.MethodTooLargeException`

### ISSUE THREAD

**Issue by rsteppac** [microsoft/azure-gradle-plugins#163]
With Gradle 8.1 and the following "minimal" project setup all Gradle targets fail with the same exception if the Azure Functions plugin is part of the configuration. Commenting out the Azure Functions plugin makes the build work again.

```kotlin
plugins {
    id("org.springframework.boot") version "3.0.6"
    id("io.spring.dependency-management") version "1.1.0"
    kotlin("jvm") version "1.7.22"
    kotlin("plugin.spring") version "1.7.22"
    kotlin("kapt") version "1.7.22"

    // The plugin will cause Gradle 8.1 to fail with an exception: Method too large
    id("com.microsoft.azure.azurefunctions") version "1.12.1"
}
```
Running a `clean` (or any other target) yields a `org.objectweb.asm.MethodTooLargeException`:
```
$ ./gradlew clean --stacktrace

FAILURE: Build failed with an exception.
[..]
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'gradle-playgroud'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:84)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:77)
[..]
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: com/azure/resourcemanager/appservice/implementation/WebAppsClientImpl.$deserializeLambda$ (Ljava/lang/invoke/SerializedLambda;)Ljava/lang/Object;
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:511)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:211)
        ... 15 more
```

The same project setup works with Gradle 8.0.

**Comment by Flanker32** [comment]
@rsteppac Thanks a lot for your report, we will investigate this issue soon

**Comment by rsteppac** [comment]
@Flanker32 , I just tried the same setup with Gradle `8.1.1` and that works. So it might not be the plugin's fault after all?

Gradle
* 8.0 works
* 8.1 works not
* 8.1.1 works
