### ISSUE TITLE
Plugin does not play nicely with Gradle's configuration cache

### ISSUE THREAD

**Issue by noetro** [microsoft/azure-gradle-plugins#188]
Trying to run any build with this plugin present AND configuration cache enabled you will note that this plugin violates the configuration cache rule by starting an external process in he configuration phase.

https://docs.gradle.org/8.10/userguide/configuration_cache.html

You can get the MAC address of a machine using the Java libraries instead of launching a process.

https://www.baeldung.com/java-mac-address

`Cause 4: org.gradle.api.InvalidUserCodeException: Starting an external process '/sbin/ifconfig -a || /sbin/ip link' during configuration time is unsupported.
        at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
        at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
        at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.getImplicitThrowable(DefaultProblemDiagnosticsFactory.java:165)
        at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.forCurrentCaller(DefaultProblemDiagnosticsFactory.java:154)
        at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1.build(DefaultProblemFactory.kt:89)
        at org.gradle.internal.cc.impl.initialization.DefaultConfigurationCacheProblemsListener.onExternalProcessStarted(ConfigurationCacheProblemsListener.kt:96)
        at org.gradle.internal.cc.impl.InstrumentedInputAccessListener.externalProcessStarted(InstrumentedInputAccessListener.kt:110)
        at org.gradle.internal.classpath.Instrumented.externalProcessStarted(Instrumented.java:458)
        at org.gradle.internal.classpath.Instrumented.externalProcessStarted(Instrumented.java:466)
        at org.gradle.internal.classpath.Instrumented.start(Instrumented.java:320)
        at com.microsoft.azure.toolkit.lib.common.utils.NetUtils.getMacsByCommand(NetUtils.java:108)
        at com.microsoft.azure.toolkit.lib.common.utils.NetUtils.getMacByCommand(NetUtils.java:96)
        at com.microsoft.azure.toolkit.lib.common.utils.NetUtils.getMac(NetUtils.java:88)
        at com.microsoft.azure.toolkit.lib.common.utils.InstallationIdUtils.getHashMac(InstallationIdUtils.java:29)
        at com.microsoft.azure.plugin.functions.gradle.AzureFunctionsPlugin.lambda$apply$8(AzureFunctionsPlugin.java:88)
`

**Comment by leontodd** [comment]
also seeing this issue. huge negative effect on build times in a monorepo without configuration cache
