### ISSUE TITLE
Plugin produces exception when used in a multi project build

### ISSUE THREAD

**Issue by graemerocher** [microsoft/azure-gradle-plugins#46]
When using the plugin as a subproject in a multi-project build the following error occurs:

```
java.io.IOException: Resource not found: /version.txt
        at org.apache.commons.io.IOUtils.resourceToURL(IOUtils.java:1372)
        at org.apache.commons.io.IOUtils.resourceToString(IOUtils.java:1293)
        at org.apache.commons.io.IOUtils.resourceToString(IOUtils.java:1272)
        at com.microsoft.azure.plugin.functions.gradle.telemetry.TelemetryAgent.<init>(TelemetryAgent.java:64)
        at com.microsoft.azure.plugin.functions.gradle.telemetry.TelemetryAgent.<clinit>(TelemetryAgent.java:60)
        at com.microsoft.azure.plugin.functions.gradle.AzureFunctionsPlugin.apply(AzureFunctionsPlugin.java:27)
        at com.microsoft.azure.plugin.functions.gradle.AzureFunctionsPlugin.apply(AzureFunctionsPlugin.java:19)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:181)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
```

To reproduce checkout https://github.com/micronaut-projects/micronaut-starter

Then uncomment the plugin from `starter-azure-function/build.gradle`

Then run `./gradlew assemble` you will see the exception

**Comment by andxu** [comment]
@graemerocher  Thank you for your observation, I can repro using  your repo, I will fix it in next release(not more than 4 weeks)
![image](https://user-images.githubusercontent.com/17075863/79930931-52e87a80-847c-11ea-94f9-f4284069c677.png)

**Comment by andxu** [comment]
https://github.com/microsoft/azure-gradle-plugins/pull/47

**Comment by andxu** [comment]
Release new version 1.2.0

**Comment by graemerocher** [comment]
Thank you!
