### ISSUE TITLE
Creating an azure http function project using mn results in a broken build

### ISSUE THREAD

**Issue by mbjarland** [microsoft/azure-gradle-plugins#63]
### Description 
Creating a azure http function project with mn (and gradle, groovy, and spock) results in a broken gradle build. 

### Steps to reproduce 
```
─➤ mn 
> create-app azure-function-context-path-issue --lang groovy --build gradle --java-version 8 --test spock --features azure-function --features 
> exit
─➤ cd azure-function-context-path-issue
─➤ ./gradlew build
... 
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :compileGroovy FAILED
startup failed:
General error during conversion: java.lang.NoClassDefFoundError: io.micronaut.servlet.http.ServletHttpHandler

java.lang.RuntimeException: java.lang.NoClassDefFoundError: io.micronaut.servlet.http.ServletHttpHandler
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:955)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:650)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:606)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:277)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:67)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:98)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:77)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io.micronaut.servlet.http.ServletHttpHandler
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:46)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:79)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:70)
        at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createFieldNode(MemberSignatureParser.java:160)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lambda$createFieldNode$0(DecompiledClassNode.java:220)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.createFieldNode(DecompiledClassNode.java:226)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:210)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:122)
        at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:866)
        at org.codehaus.groovy.ast.ClassNode.hasPossibleMethod(ClassNode.java:1260)
        at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:288)
        at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:131)
        at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitReturnStatement(ClassCodeExpressionTransformer.java:126)
        at org.codehaus.groovy.ast.stmt.ReturnStatement.visit(ReturnStatement.java:73)
        at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:164)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
        at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:66)
        at org.codehaus.groovy.control.StaticImportVisitor.visitConstructorOrMethod(StaticImportVisitor.java:106)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:106)
        at org.codehaus.groovy.ast.ClassNode.visitMethods(ClassNode.java:1100)
        at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1093)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
        at org.codehaus.groovy.control.CompilationUnit.lambda$addPhaseOperations$3(CompilationUnit.java:207)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:921)
        ... 35 more
```
### Expected behavior
A working project. 

### Actual behavior
A broken build. 

### Analysis and Potential Fix
The relevant class lives in the dependency `io.micronaut.servlet:micronaut-servlet-core` which in the newly created project is only defined for gradle configuration `testImplementation` and not for `implementation`. In other words, the application classes will not know about this class and the build fails. 

Adding: 

```
    implementation("io.micronaut.servlet:micronaut-servlet-core")
```

to the `build.gradle` file in the newly created project fixes the issue. 

### NOTE: 
Quoting discussion on gitter with Graeme Rocher: 
```
Graeme Rocher @graemerocher 15:53
it [adding a direct dependency] shouldn’t be needed as that it a transitive dependency of micronaut-function-http
if that is happening it is probably another bug in the Azure plugins
similar to microsoft/azure-maven-plugins#1051
```
i.e. it seems that this should be handled by a transitive dependency and not by a direct one. Also Graeme informed me that this issue needs to move from: 

```
https://github.com/micronaut-projects/micronaut-azure/issues
```
to 
```
https://github.com/microsoft/azure-gradle-plugins/issues
```
which is where it now lives. I closed the original issue at `micronaut-azure`. 

### Environment Information
```
─➤ mn --version 
Micronaut Version: 2.0.0
JVM Version: 1.8.0_252

─➤ ./gradlew -version                                                                                              1 ↵

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_252 (Amazon.com Inc. 25.252-b09)
OS:           Linux 5.4.0-39-generic amd64
```

### Example Application

As this issue is about the templating done by `mn`, I don't think a sample repository is relevant. If you would still like to have one, I can create one. 

### Dependency Analysis
Test classpath: 
```
─➤ ./gradlew dependencyInsight --dependency 'micronaut-servlet-core' --configuration testCompileClasspath

> Task :dependencyInsight
io.micronaut.servlet:micronaut-servlet-core:1.0.0 (by constraint)
   variant "apiElements" [
      org.gradle.category            = library
      org.gradle.dependency.bundling = external
      org.gradle.jvm.version         = 8
      org.gradle.libraryelements     = jar (compatible with: classes+resources)
      org.gradle.usage               = java-api
      org.gradle.status              = release (not requested)
   ]

io.micronaut.servlet:micronaut-servlet-core:1.0.0
\--- io.micronaut:micronaut-bom:2.0.0
     \--- testCompileClasspath

io.micronaut.servlet:micronaut-servlet-core -> 1.0.0
\--- testCompileClasspath

A web-based, searchable dependency report is available by adding the --scan option.
```
app classpath: 
```
─➤ ./gradlew dependencyInsight --dependency 'micronaut-servlet-core' --configuration compileClasspath

> Task :dependencyInsight
No dependencies matching given input were found in configuration ':compileClasspath'

BUILD SUCCESSFUL in 442ms
1 actionable task: 1 executed
```

also adding an online build scan with a search for `micronaut-servlet-core`: 

https://scans.gradle.com/s/jbtvkmkb7hxni/dependencies?dependencies=micronaut-servlet-core&expandAll

**Comment by graemerocher** [comment]
Actually seems to be a Groovy bug

**Comment by mbjarland** [comment]
Closing this issue as it seems I filed this was files in the wrong forum.
